### ISSUE TITLE
Function documentation obscured by header when direct linking

### ISSUE THREAD

**Issue by tadman** [colby-swandale/ruby-api#102]
Methods end up hidden beneath the header when links to them are clicked as they're correctly arranged at the top of the page, but the header is fixed and overlaps. (Safari)

A small header-height offset should be applied to orient these correctly.

[Example for `String#strip!`](https://ruby-api.org/2.6/o/string#method-i-lstrip!).

**Comment by colby-swandale** [comment]
I pushed a few for this about ~12 hours ago, but there is a very good chance that the pages are still in the Cloudflare cache. Can you check if this is still a problem?

**Comment by tadman** [comment]
Looks great now!
👍
