### ISSUE TITLE
Limit search input length

### ISSUE THREAD

**Issue by tadman** [colby-swandale/ruby-api#103]
It appears that the search field accepts input of unlimited length which may present a denial-of-service risk.

For example, searching for an arbitrary 4,096 character long string takes a significant amount of time and a 65,535 long character string seems to take forever.

Truncating that to a reasonable 255 characters server-side may avoid problems like this.

**Comment by colby-swandale** [comment]
This is very reasonable and something we should defiantly do. 255 characters is a good upper limit, i can't think of a scenario when someone would need more than that.

Did you want to make a PR for this?

**Comment by ioquatix** [comment]
255 characters should be enough for anyone

**Comment by colby-swandale** [comment]
Added in 4dd5bc497cf6c5312e751449dab5a7d77d8b4490
